version: '3.7'

services:
  api:
    build: ./resume-management-api
    ports:
      - '3000:3000'
    volumes:
      - './resume-management-api/src/:/usr/app/src/'
      - './resume-management-api/config/:/usr/app/config/'
    links:
      - database

  database:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: resume_management
